import { useState } from "react";
import { Link } from "react-router-dom";
import { ChevronDown, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const fadeUp = { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.4, ease: "easeOut" } };

const faqs = [
  {
    category: "Safety & trust",
    questions: [
      { q: "Is WonderCast safe for young children?", a: "Yes — child safety is the foundation WonderCast is built on. Every topic passes two layers of safety checks: a client-side filter before you even submit, and a server-side validation before any AI touches it. Explicit content, graphic violence, sexual content, and other harmful material are blocked entirely. Language is automatically calibrated to be age-appropriate — a 3-year-old's episode sounds and reads completely differently from a 14-year-old's." },
      { q: "Can I review the script before my child listens?", a: "Yes. WonderCast shows you a full preview of the script before you generate audio. You can read every word, regenerate the script if you'd like a different angle, or go back and adjust the topic. Nothing is sent to audio until you choose to." },
      { q: "What topics are blocked?", a: "WonderCast blocks explicit content, graphic violence, sexual content, content involving self-harm, hate speech, terrorism, and other material that is clearly inappropriate for children. Sensitive topics — like war, death, or political subjects — are flagged for children under 16 with a suggestion to approach them differently. The goal is thoughtful restriction, not blanket censorship of serious or educational topics." },
      { q: "Who built WonderCast and what AI does it use?", a: "WonderCast uses Claude (by Anthropic) to write scripts. Claude is one of the most safety-focused AI models available, built by a company whose mission is responsible AI development. Voice audio is generated by ElevenLabs. Both are industry-leading tools used by millions of developers worldwide." },
    ],
  },
  {
    category: "The product",
    questions: [
      { q: "What age group is WonderCast designed for?", a: "WonderCast is designed for children aged 3 to 16. You choose from seven age bands: 3–4, 5–6, 7–8, 9–10, 11–12, 13–14, and 15–16. Each band has distinct settings for vocabulary complexity, episode length, narration pace, voice style, and learning depth. The same topic — say, 'how the ocean works' — produces a completely different episode for a 4-year-old versus a 13-year-old." },
      { q: "How long does it take to generate an episode?", a: "Script generation takes about 10–20 seconds. Voice audio generation takes an additional 15–40 seconds depending on episode length. A 3-minute episode for a young child is ready in under 30 seconds. A 15-minute lesson for a teenager takes closer to a minute." },
      { q: "Can I save episodes to listen to again?", a: "Yes. Every generated episode can be saved to your Library from the Listen screen. Your library persists between sessions. In a future update, audio files will be stored permanently so saved episodes can always be replayed." },
      { q: "What formats does WonderCast support?", a: "WonderCast generates two types of content: Stories (narrative-led, character-driven, ideal for younger children and bedtime) and Lessons (structured, explanation-led, ideal for older children and school help). Both formats are available at every age level." },
      { q: "Can I customise the voice and style?", a: "Yes. Advanced Controls (hidden under an expandable menu so they don't overwhelm) let you choose voice style (warm female, warm male, animated storyteller, calm narrator, teacher-style), speaker setup (one narrator, two speakers, narrator + character, parent-style explainer), tone, energy level, learning depth, and safety sensitivity level." },
    ],
  },
  {
    category: "Topics and content",
    questions: [
      { q: "What topics can WonderCast cover?", a: "Almost any age-appropriate topic. Science (how volcanoes work, why the sky is blue, how the human body works), history (ancient Egypt, the Romans, World War II for older children), geography, nature, animals, space, maths concepts, emotions and relationships, current events (age-appropriate), literature themes, and anything else a curious child might wonder about. The only limit is what's appropriate for children." },
      { q: "What if my topic is too complex?", a: "WonderCast evaluates every topic for complexity as you type. If a topic is too abstract, too multi-layered, or uses overly academic language for a single short episode, you'll see a friendly suggestion to simplify it — with a concrete example of a simpler way to approach the same idea. The goal is to make great content, not just any content." },
      { q: "Can WonderCast help with school homework?", a: "Yes — the 'School Help' situation preset is designed exactly for this. Type any school subject or topic (e.g. 'explain the water cycle', 'how does photosynthesis work', 'what caused World War I') and WonderCast generates a clear, engaging explanation at your child's exact age level. It's like a patient tutor who can explain anything in plain language." },
      { q: "Can I request a specific story character or setting?", a: "You can include character or setting details in your topic — for example, 'a story about a girl who discovers how volcanoes work' or 'a lesson about ancient Rome told through the eyes of a young Roman'. WonderCast's AI will work with whatever direction you give it within the topic field." },
    ],
  },
  {
    category: "Pricing and access",
    questions: [
      { q: "Is WonderCast free?", a: "WonderCast is currently free to use. No account, no credit card, no subscription required. Create an episode by choosing your child's age, typing a topic, and pressing Create Audio." },
      { q: "Do I need to create an account?", a: "Not yet. WonderCast works without an account. Your saved library is stored in your browser. In a future update, accounts will allow you to access your library across devices and create separate profiles for different children." },
      { q: "Will WonderCast always be free?", a: "The current free version will always be available. A future premium version may offer features like unlimited library storage, saved audio files, multiple child profiles, and additional voice options. The core episode generation experience will remain free." },
    ],
  },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-2xl border border-[#E7B05E]/30 bg-white/70 backdrop-blur overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center justify-between gap-4 p-5 text-left"
        aria-expanded={open}
      >
        <span className="font-black text-[#1B203A]">{q}</span>
        <ChevronDown size={18} className={`shrink-0 text-[#A74921] transition-transform duration-200 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22, ease: "easeOut" }}
            className="overflow-hidden"
          >
            <p className="border-t border-[#E7B05E]/20 px-5 pb-5 pt-4 text-sm font-medium leading-7 text-[#7F3E28]">{a}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQPage() {
  return (
    <motion.div {...fadeUp} className="pb-20">

      {/* Hero */}
      <section className="mb-14 rounded-[34px] border border-[#E7B05E]/30 bg-white/70 p-8 text-center shadow-[0_24px_90px_rgba(0,0,0,0.08)] backdrop-blur sm:p-12">
        <h1 className="mb-4 text-4xl font-black text-[#1B203A] sm:text-5xl">Frequently asked questions</h1>
        <p className="mx-auto max-w-xl text-lg font-medium leading-8 text-[#7F3E28]">
          Everything parents want to know about WonderCast — safety, content, how it works, and what's coming next.
        </p>
      </section>

      {/* FAQ sections */}
      <div className="space-y-12">
        {faqs.map(({ category, questions }) => (
          <section key={category} aria-labelledby={`cat-${category}`}>
            <h2 id={`cat-${category}`} className="mb-5 flex items-center gap-3 text-lg font-black text-[#1B203A]">
              <span className="h-px flex-1 bg-[#E7B05E]/40" />
              <span className="rounded-full bg-[#E7B05E]/30 px-4 py-1.5 text-sm font-black text-[#A74921]">{category}</span>
              <span className="h-px flex-1 bg-[#E7B05E]/40" />
            </h2>
            <div className="space-y-3">
              {questions.map(({ q, a }) => <FAQItem key={q} q={q} a={a} />)}
            </div>
          </section>
        ))}
      </div>

      {/* Still have questions */}
      <div className="mt-16 rounded-[28px] border border-[#E7B05E]/30 bg-white/70 p-8 text-center backdrop-blur">
        <p className="mb-2 text-xl font-black text-[#1B203A]">Still have a question?</p>
        <p className="mb-6 text-sm font-medium text-[#7F3E28]">The best way to understand WonderCast is to try it. It takes less than a minute to create your first episode — no account needed.</p>
        <Link to="/" className="inline-flex items-center gap-2 rounded-2xl bg-[#A74921] px-8 py-4 font-black text-white shadow-[0_12px_30px_rgba(167,73,33,0.3)] transition hover:bg-[#8a3a1a]">
          <Sparkles size={18} /> Create a free episode
        </Link>
      </div>

    </motion.div>
  );
}
